### ISSUE TITLE
Error when updating webppl

### ISSUE THREAD

**Issue by dfilan** [agentmodels/agentmodels.org#17]
After pulling the latest version of agentmodels.org, when I run `sudo sh ./scripts/update-webppl`, I get the following error message which stops the update:

```
Warning: Command failed: browserify -t [./src/bundle.js --require ../webppl-timeit --require ../webppl-dp --require ../webppl-viz --require ../webppl-gridworld] -g brfs src/browser.js -o bundle/webppl.js
Error: Line 479: Unexpected token < (/Users/danielfilan/Documents/fhi_internship/agentmodels.org/node_modules/webppl-viz/src/index.js) while parsing file: /Users/danielfilan/Documents/fhi_internship/agentmodels.org/node_modules/webppl-viz/src/index.js
at Stream.end (/Users/danielfilan/Documents/fhi_internship/agentmodels.org/node_modules/webppl/node_modules/brfs/index.js:39:32)
at _end (/Users/danielfilan/Documents/fhi_internship/agentmodels.org/node_modules/webppl/node_modules/through/index.js:61:9)
at Stream.stream.end (/Users/danielfilan/Documents/fhi_internship/agentmodels.org/node_modules/webppl/node_modules/through/index.js:70:5)
at DestroyableTransform.onend (/usr/local/lib/node_modules/browserify/node_modules/readable-stream/lib/_stream_readable.js:545:10)
at DestroyableTransform.g (events.js:260:16)
at emitNone (events.js:72:20)
at DestroyableTransform.emit (events.js:166:7)
at endReadableNT (/usr/local/lib/node_modules/browserify/node_modules/readable-stream/lib/_stream_readable.js:960:12)
at nextTickCallbackWith2Args (node.js:441:9)
at process._tickCallback (node.js:355:17)
Use --force to continue.

Aborted due to warnings.
```

I'm not sure what the problem is: line 479 of `node_modules/webppl-viz/src/index.js` looks unremarkable to me.

**Comment by owainevans** [comment]
looks like that line should be returning a string containing the html, not
the raw html. (but i haven't checked).
https://github.com/probmods/webppl-viz/blob/master/src/index.js#L479

either wait till later tonight to update webppl or you'd want to install an
earlier commit of viz by editing the install script appropriately.
